### ISSUE TITLE
Create a `data` dir

### ISSUE THREAD

**Issue by YacineSteeve** [YacineSteeve/quizoot#58] opened 2022-12-15 10:50 UTC
- [ ] create a data dir with dummy quizzes and questions.

Must be a top level dir ?
<br/>
>
> __PRIORITY__ : MEDIUM
>

**Comment by chrichri17** [comment] 2022-12-15 12:01
This is a duplicate of issue #22. I mean it's included in #22

**Comment by YacineSteeve** [comment] 2022-12-15 17:55
You're right. But I prefer a fresh issue instead of reopening #22

**Closed as completed** 2023-02-19 17:09 UTC
Labels: help wanted
